# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Tour
    url: tour
    weight: 10
  - name: News
    url: post
    weight: 20
  - name: Team
    url: people
    weight: 30
  - name: Events
    url: event
    weight: 40

  - name: Research
    identifier: research
    # url: research
    weight: 50
  - name: Intelligent Network
    parent: research
    url: research/intelligent_network/
    weight: 10
  - name: Edge Intelligence
    parent: research
    url: research/edge_intelligence/
    weight: 20
  - name: Smart IoT
    parent: research
    url: research/smart_iot/
    weight: 30
  - name: Publications
    url: publication
    weight: 60
  - name: Open Resource
    url: open_resource
    weight: 70
  - name: Join us
    url: publication
    weight: 80
  - name: Contact
    url: contact
    weight: 90
